# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cubby < Formula
  desc "CLI for CubbyDrop — zero-knowledge encrypted file sharing"
  homepage "https://cubbydrop.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.cubbydrop.com/cubby/v0.1.0/cubby_0.1.0_darwin_amd64.tar.gz"
      sha256 "6695b74c0697f5904aa16569d901231bf4bb5b5101942536a881024323fcd9e8"

      define_method(:install) do
        bin.install "cubby"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.cubbydrop.com/cubby/v0.1.0/cubby_0.1.0_darwin_arm64.tar.gz"
      sha256 "de96dfc9ca5bca654a87ce54081ed539cf4564c2a43342aae0f46cc2a499d09c"

      define_method(:install) do
        bin.install "cubby"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.cubbydrop.com/cubby/v0.1.0/cubby_0.1.0_linux_amd64.tar.gz"
      sha256 "5cda55d86b36e229a4705706e5890867fd2435be5ff6c645447645805053e6e3"
      define_method(:install) do
        bin.install "cubby"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.cubbydrop.com/cubby/v0.1.0/cubby_0.1.0_linux_arm64.tar.gz"
      sha256 "83d5187a99daf607b20e6ee65530d8f8df0b0368e02829e4bb07915403e95f72"
      define_method(:install) do
        bin.install "cubby"
      end
    end
  end
end
