# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cubby < Formula
  desc "CLI for CubbyDrop — zero-knowledge encrypted file sharing"
  homepage "https://cubbydrop.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.cubbydrop.com/cubby/v0.1.0/cubby_0.1.0_darwin_amd64.tar.gz"
      sha256 "dc71b9fdf35e145bd8996c1a7f13c3c6edcc542f293b4a40b2f0bfd3a8752795"

      define_method(:install) do
        bin.install "cubby"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.cubbydrop.com/cubby/v0.1.0/cubby_0.1.0_darwin_arm64.tar.gz"
      sha256 "bf29bdbaaa42b69e9a2eede78badb018fa0227040fb74555a1f59ab6fa9d2d09"

      define_method(:install) do
        bin.install "cubby"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.cubbydrop.com/cubby/v0.1.0/cubby_0.1.0_linux_amd64.tar.gz"
      sha256 "589457c80f80575a61842d7f60003e2f5e7480da6c397e50e5d07e4b5eb3049e"
      define_method(:install) do
        bin.install "cubby"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.cubbydrop.com/cubby/v0.1.0/cubby_0.1.0_linux_arm64.tar.gz"
      sha256 "51fdedd7d159a1d0abbd5ede840ff8fecf747bbdbbf1fc7c8e05ad9549eecaca"
      define_method(:install) do
        bin.install "cubby"
      end
    end
  end
end
